### ISSUE TITLE
soft-hyphen gives empty form

### ISSUE THREAD

**Issue by unhammer** [apertium/lttoolbox#113]
There's a literal nbsp after [] here, giving an empty form for some reason:
```
$ echo '.[]­' |  lt-proc -w -e 'nob-nno.automorf.bin'
^/.<sent><clb>$[]­

```

**Comment by TinoDidriksen** [comment]
That's not an NBSP (U+00A0). It's a soft hyphen (U+00AD).

To prevent copy-paste issues, this can also be written as:
  `printf '.[]\u00ad\n' | lt-proc -w -e nob-nno.automorf.bin`

or in case printf doesn't understand \u, then
  `printf '.[]\xc2\xad\n' | lt-proc -w -e nob-nno.automorf.bin`

Because NBSP works as expected, while SHY does not.

**Comment by unhammer** [comment]
Doh, right you are. That's even worse, those things are everywhere :-/

**Comment by Shreyansh252001** [comment]
@unhammer  Can you please tell me the file you are talking about and what is the thing you want to rectify and what is the thing to add?

**Comment by TinoDidriksen** [comment]
There is no file. And it's something that needs fixing in the lttoolbox code.

**Comment by TinoDidriksen** [comment]
https://github.com/apertium/lttoolbox/issues/50

**Comment by unhammer** [comment]
fixed in https://github.com/apertium/lttoolbox/commit/848abfe5b0a6ff88e0f46fb5a4d0fc8d26ba5628
