### ISSUE TITLE
lt-comp --var-left

### ISSUE THREAD

**Issue by hectoralos** [apertium/lttoolbox#51]
"lt-comp --var-left" is used in several Makefile, but it does not appear if I type
lt-comp --help

**Comment by unhammer** [comment]
(Seems like `--help` only shows the short options, `man lt-comp` fortunately shows the long ones as well)

**Comment by hectoralos** [comment]
So, -l and --var-left should be synonyms. It's very strange, but seemingly they are not. I had problems with -l and the problem was solved using --var-left: https://github.com/apertium/apertium-por-cat/commit/ef71b940b3ee85d158a9cb57a8cdc846aaa4675e

**Comment by AMR-KELEG** [comment]
Hi @hectoralos I have tested the lt-comp script and actually yes -l and --var-left are synonyms.

The problem is that short and long options are set in different ways.
So, if you wanted to use `-l` for the following command:
`lt-comp --var-left=br rl $< $@`
You would write it as follows:
`lt-comp -l br rl $< $@`

If you an equal exists after the `-l` (`lt-comp -l=br rl $< $@`) then the value that the compiler will parse from the command options is `=br` and not `br`.
